In [1]:
import numpy as np
arr = np.ones((3,3), dtype=bool)
print(arr)
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3,3)
print(arr_2D)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print(arr_2D)
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print(arr_2D)
arr_2D = arr_2D[::-1, :]
print(arr_2D)
arr_2D = arr_2D[:, ::-1]
print(arr_2D)
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()
print(has_nan)
arr_2D_null[np.isnan(arr_2D_null)] = 0
print(arr_2D_null)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[5 4 3]
 [2 1 0]
 [8 7 6]]
[[8 7 6]
 [2 1 0]
 [5 4 3]]
[[6 7 8]
 [0 1 2]
 [3 4 5]]
True
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
