In [ ]:
!python -m pip install --upgrade pip 
!python -m pip install numpy

In [ ]:
import numpy as np
np.__version__

'2.3.4'

In [ ]:
import numpy as np
import sys 
S = list(range(1000))
items_S = sys.getsizeof(S)     
print("Kích thước của danh sách S (bytes):", items_S)
S_size = items_S * len(S)
print("Kích thước ước lượng toàn bộ List (bytes):", S_size)
D = np.arange(1000) 
print("Kích thước mỗi phần tử trong NumPy array (bytes):", D.itemsize)
array_size = D.itemsize * D.size
print("Kích thước của toàn bộ NumPy array (bytes):", array_size)
print(f"Tỷ lệ (list/array): {S_size / array_size:.2f}")

Kích thước của danh sách S (bytes): 8056
Kích thước ước lượng toàn bộ List (bytes): 8056000
Kích thước mỗi phần tử trong NumPy array (bytes): 8
Kích thước của toàn bộ NumPy array (bytes): 8000
Tỷ lệ (list/array): 1007.00


In [ ]:
tong = 0
for i in range(100):
    tong += i
print(tong)

4950


In [ ]:
arr = np.array([1.5, 3.7, 2.2])
arr
arr.dtype

dtype('float64')

In [ ]:
arr_int = arr.astype(np.int32)
arr_int 
print(arr_int, arr_int.dtype)

[1 3 2] int32


In [ ]:
print(arr, arr.dtype)

[1.5 3.7 2.2] float64


In [ ]:
import numpy as np
arr_int = np.array([1, 2, 3, 4], dtype=np.int32)
arr_int.dtype

dtype('int32')

In [ ]:
print(arr_int)
print(type(arr_int))

In [ ]:
arr_string = np.array(['apple', 'banana', 'cherry'], dtype=np.str)
print(arr_string)
print(arr_string.dtype)

In [ ]:
my_list = [1, 2, 3, 4, 5]
arr_1 = np.array(my_list)
print(arr_1)
arr_1.dtype

[1 2 3 4 5]


dtype('int64')

In [ ]:
my_list = [1, 2, 3, 4, 5]
arr_2 = np.array([my_list], dtype=float)
print(arr_2)
arr_2.dtype

[[1. 2. 3. 4. 5.]]


dtype('float64')

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
arr_3 = np.array(my_tuple)
print(arr_3)
arr_3.dtype

In [ ]:
arr_4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_4)
arr_4.dtype

In [ ]:
a0= np.zeros(5,dtype=int)
a0

array([0, 0, 0, 0, 0])

In [ ]:
a0.dtype

In [ ]:
a1= np.ones((3,3),dtype=float)
a1
a1.dtype

dtype('float64')

In [ ]:
np.full((5,5),100,dtype=int)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [ ]:
arr_1 = np.linspace(0, 10, 5)
print(arr_1)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr_2 = np.linspace(0, 1, 10, endpoint=False)
print(arr_2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
arr_3, step = np.linspace(1, 10, 100, retstep=True)
print(arr_3)
print("Bước giữa các phần tử:", step)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [ ]:
arr_6 = np.radom.normal(loc=0.0, scale=1.0, size=(100))
print(arr_6)

In [ ]:
arr_7 = np.random.randint(low=0, high=10, size=(3,3))
print(arr_7)

[[1 0 3]
 [2 4 8]
 [2 0 3]]


In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(5)

array([0., 2., 4., 6., 8.])

In [ ]:
arr = np.array([[1, 2, 3],[ 4, 5, 6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr.strides)
print("Tong theo truc 0 (theo cot)", arr.sum(axis=0))
print("Tong theo truc 1 (theo hang)", arr.sum(axis=1))    

2
(2, 3)
6
int64
8
48
(24, 8)
Tong theo truc 0 (theo cot) [5 7 9]
Tong theo truc 1 (theo hang) [ 6 15]


In [ ]:
arr_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
np.sum(arr_a)
print(np.sum(arr_a, axis=0))  
print(np.sum(arr_a, axis=1))


[15 18 21 24]
[10 26 42]


In [ ]:
A= np.array([1, 2, 3, 4, 5])
A[0]
A[4]
A[-1]
A[-2]

In [ ]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B(0,0)
B(2,0)
B(2, -1)
B(0,0)= 0
np.array(B)

In [ ]:
arr = [0,1,2,3,4,5,6,7,8,9]
arr[3:]
arr[-3:]
arr[:10]
arr[3::1]

In [ ]:
import numpy as np
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr
print("Cột đầu tiên của mảng arr là: ",arr[:,0])
print("Hàng đầu tiên của mảng arr là:",arr[0,:])
print("Hàng đầu tiên của mảng arr là:",arr[0])

Cột đầu tiên của mảng arr là:  [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
arr_view = arr_2d[:2, :2].view()
print(arr_view)
arr_view[0, 0] = 100
print(arr_view)
print("Mảng gốc sau khi thay đổi giá trị trong view:")
print(arr_2d)

[[1 2]
 [4 5]]
[[100   2]
 [  4   5]]
Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
sub_arr_copy=arr[:2,:2].copy()
print(sub_arr_copy)
sub_arr_copy[0,0]=10 
print(sub_arr_copy)
print(arr)

In [ ]:
arr=np.arange(1,10) 
grid= arr.reshape((3,3))
grid

In [ ]:
import numpy as np
x = np.arange([1, 2, 3])
x.reshape((1,3))
y =x[np.newxais: ]
print(x)
print("Them 1 hang")
print(y)
z = x[:, np.newaxis]
print("Them 1 cot")
print(z)
x.reshape((3,1))
np.ndim(x)


In [ ]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y])



In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])  
np.concatenate([a, b])
np.vstack([a, b])
np.hstack([a, b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
import numpy as np
arr = np.arange(10) 
sub_arr1=np.split(arr,[3, 6]) 
sub_arr2=np.split(arr,2) 
print("Mảng con sub_arr1 là:", sub_arr1, "\n")
print("Mảng con sub_arr2 là:", sub_arr2)

In [ ]:
import numpy as np
arr = np.arange(16).reshape((4,4))
arr
upper, lower = np.vsplit(arr, [2])
print("Phần trên của mảng sau khi tách:\n", upper)
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(upper,"\n")
print(lower,"\n")
left,right=np.hsplit(arr,2) #Tách theo trục dọc
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(left,"\n")
print(right,"\n")


In [ ]:
import numpy as np
arr=np.array([1,2,3])
new_arr=np.append(arr,4)
print(arr)
print(new_arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
new_element = 10
index_to_insert = 2
new_arr = np.insert(arr, index_to_insert, new_element)
print(new_arr)

In [ ]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
new_element = [7, 8]
row_to_insert = 1
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0)
print(new_arr_2d)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr==3)
indices

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.argwhere(arr==3)
indices

In [ ]:
arr = np.array([1, 5, 2, 3, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print(max_idx)
print(min_idx)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
sorted_arr = np.sort(arr)
sorted_arr

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.sort()
arr

In [ ]:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending

In [ ]:
arr = np.array([3, 1, 4, 2, 5])
arr.sort()
arr[::-1]

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_idx_to_delete = 1
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
del arr
arr

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr = None
print(arr)

In [ ]:
import numpy as np
dtype = [('name', 'U20'), ('age', int), ('height', float)]
data = np.array([('Minh', 22, 181.3),
                ('Lan', 40, 160.6),
                ('Linh', 31, 163.2),
                ('Lương',18,175.5),
                ('Thanh',50, 165.0)], dtype=dtype)
print(data)
print(data.dtype)

In [ ]:
import numpy as np
dtype = [('name', 'U20'), ('age', int), ('height', float)]
data = np.array([('Minh', 22, 181.3),
                ('Lan', 40, 160.6),
                ('Linh', 31, 163.2),
                ('Lương',18,175.5),
                ('Thanh',50, 165.0)], dtype=dtype)
rec_data = data.view(np.recarray)
rec_data

In [ ]:
import numpy as np
dtype = [('name', 'U20'), ('age', int), ('height', float)]
data = np.array([('Minh', 22, 165.5),
('Lan', 40, 160.0),
('Linh', 31, 165.0),
('Lương',18,166.5),
('Thanh',50, 170.0)], dtype=dtype)
print(data['name']) 
print(data['age']) 
print(data['height'])

In [ ]:
import numpy as np
import time

arr = np.arange(100000000, dtype=np.int64)
start_time = time.time()
total = np.int64(0)
for num in arr:
    total += num
end_time = time.time()
elapsed_time_loop = end_time - start_time

print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total)
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop)

# --- Cách 2: Tính tổng bằng hàm np.sum() ---
start_time = time.time()
total = np.sum(arr)
end_time = time.time()
elapsed_time_npsum = end_time - start_time

print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total)
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum)

num_times_faster = elapsed_time_loop / elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn khoảng:", int(num_times_faster), "lần")


Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 18.53691339492798
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.10339903831481934
Sử dụng vòng lặp chậm hơn khoảng: 179 lần


In [ ]:
import numpy as np
import timeit 
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)"
np_code = "np_sum = np.sum(np_array)"
np_time = timeit.timeit(stmt=np_code, setup=np_setup, number=10)
list_setup = "list_array = list(range(1, 1000001))"
list_code = "list_sum = sum(list_array)"
list_time = timeit.timeit(stmt=list_code, setup=list_setup,
number=10)
print("Thời gian tính toán của Numpy:", np_time)
print("Thời gian tính toán của List:", list_time)
print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")

Thời gian tính toán của Numpy: 0.00848509999923408
Thời gian tính toán của List: 0.09180499997455627
Numpy tính nhanh hơn List ở lượt chạy là ~  10 lần!!


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
Tong = np.add(arr1,arr2)
Hieu = np.subtract(arr1,arr2)
Tich = np.multiply(arr1,arr2)
Thuong = np.divide(arr1,arr2)
print("Tổng của arr1 + arr2 là:",Tong)
print("Hiệu của arr1 - arr2 là:",Hieu)
print("Tích của arr1 * arr2 là:",Tich)
print("Thương của arr1/arr2 là:",Thuong)

Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1/arr2 là: [0.25 0.4  0.5 ]


In [ ]:
import numpy as np
arr1=np.random.rand(5)
arr1
arr2=np.random.rand(5)
arr2
arr_maximum=np.maximum(arr1,arr2)
print("Mảng kết quả là:",arr_maximum)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Căn bậc hai của các phần tử trong mảng
kq_can_hai = np.sqrt(arr)
# Lũy thừa 2 của các phần tử trong mảng
kq_luy_thua_2 = np.power(arr, 2)
# Logarit tự nhiên (cơ số e) của các phần tử trong mảng
kq_Logarit = np.log(arr)
# Giá trị tuyệt đối của các phần tử trong mảng
kq_tri_tuyet_doi = np.abs(arr)
# Hàm logic NOT (đảo ngược giá trị) của các phần tử trong mảng
kq_not_logic = np.logical_not(arr)
#Hàm sin của các phần tử trong mảng
kq_sin=np.sin(arr)
print("Căn bậc hai của từng phần tử trong mảng là: ", kq_can_hai)
print("Lũy thừa bậc hai của từng phần tử trong mảng là: ", kq_luy_thua_2)
print("Logarit của từng phần tử trong mảng là: ", kq_logarit)
print("Trị tuyệt đối của từng phần tử trong mảng là: ", kq_tri_tuyet_doi)
print("Kết quả đảo ngược giá trị của các phần tử trong mảng là:", kq_not_logic)
print("Kết quả hàm sin của các phần tử trong mảng là:", kq_sin)

In [ ]:
import numpy as np
arr1 = np.array([0,1,2])
arr2 = np.array([5,5,5])
arr1 + arr2

In [ ]:
import numpy as np
arr1 = np.array([0,1,2])
arr1 + 5

In [ ]:
import numpy as np
arr = np.array([0,1,2])
arr
M=np.ones((3,3))
M
arr + M

In [ ]:
import numpy as np
arr1 = np.arange(3)
arr2=np.arange(3)[:,np.newaxis]
print(arr1)
print(arr2)
arr1 + arr2

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
import numpy as np
arr1=np.ones((2,3))
arr2 = np.arange(3)
print(arr1.shape)
print(arr2.shape)

In [ ]:
import numpy as np
data = np.random.randint(100, 200, size=1000)
mean_value = np.array([data.mean()])
percentage_growth= (data - mean_value) / mean_value * 100
print("Dữ liệu gốc:", data[:10])
print("Tỷ lệ phần trăm tăng trưởng:",
percentage_growth[:10])

In [ ]:
import numpy as np
output=np.zeros((3,3))
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.add(arr1,arr2, out=output)
#In kết quả
print(output)

In [ ]:
import numpy as np
visitors = np.array([10200, 9875, 13567,7900,11200, 8871, 12567])
sum = 0
for i in visitors:
    if (i>10000):
        sum+=i
print(sum)

In [ ]:
mask = visitors > 10000
mask



In [ ]:
visitors(mask)

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result1 = arr1 > arr2 
result2 = arr1 == arr2 
result3 = arr1 <= arr2 
print("Kết quả lớn hơn:", result1)
print("Kết quả bằng nhau:", result2)
print("Kết quả nhỏ hơn hoặc bằng:", result3)

Kết quả lớn hơn: [False False False  True  True]
Kết quả bằng nhau: [False False  True False False]
Kết quả nhỏ hơn hoặc bằng: [ True  True  True False False]


In [ ]:
import numpy as np
arr = np.array([[1,0,3],
[0,5,0],
[7,0,9]])
count = np.count_nonzero(arr)
count

np.int64(5)

In [ ]:
import numpy as np
diemTB = np.array([6.7, 8, 4, 5.8, 9, 8.3, 5, 7.2, 5.5])
diemTB = np.array([6.7, 8, 4, 5.8, 9, 8.3, 5, 7.2, 5.5])
boolArr=(diemTB >= 8) & (diemTB <= 10)
boolArr
np.count_nonzero(boolArr)
np.count_nonzero((diemTB >= 8) & (diemTB <= 10) )
np.sum(boolArr)



In [ ]:
import numpy as np
arr = np.array([[1,0,3],
[0,5,0],
[7,0,9]])
#Sử dụng phương thức sum kèm theo tham số axis (trục) tương ứng
print('Số phần tử khác 0 theo mỗi hàng',np.sum(arr !=0, axis=1))
print("Số phần tử khác 0 theo mỗi cột:",np.sum(arr!=0, axis=0))
print("Trong mảng arr có phần tử > 5: ", np.any(arr > 5))
print("Trong mảng arr có phần tử < 0: ", np.any(arr < 0))
print("Trong mảng arr tất cả các phần tử đều < 10: ", np.all(arr < 10))
print("Trong mảng arr tất cả các phần tử đều = 3:", np.all(arr == 3))
print("Kiểm tra từng cột trong mảng arr, \ncột nào có tất cả các phần tử lớn hơn 1: \n",
np.all(arr > 1, axis=0))

In [ ]:
import numpy as np
import numpy.ma as ma
arr = np.array([1,2,3,4,5,6,7,8,9])
mask =arr>6
masked_arr=np.ma.masked_array(arr,mask)
masked_arr

In [ ]:
valid_values = arr[~mask]
print("Dữ liệu ban đầu:", arr)
print("Mảng mask:", mask)
print("Các giá trị hợp lệ từ mảng ban đầu:", valid_values)

In [ ]:
import numpy as np
import numpy.ma as ma
#Tạo một mảng NumPy bình thường
arr = np.array([1,2,3,4,5,6,7,8,9])
# Tạo một mảng mask cho các giá trị không hợp lệ
mask =arr>6
masked_arr=np.ma.masked_array(arr,mask,fill_value=100)
print("Masked Array chưa được điền: ", masked_arr)
print("Masked Array đã điền: ", masked_arr.filled())

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
#loại các giá trị nhỏ hơn 5
masked_arr1=np.ma.masked_less(arr,5)
print("masked_arr1 :",masked_arr1)
#loại các giá trị nhỏ hơn hoặc bằng 5
masked_arr2=np.ma.masked_less_equal(arr,5)
print("masked_arr1 :", masked_arr2)

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
#Truy xuất các phần tử bằng một danh sách các chỉ mục
indices = [1, 3, 4]
sub_arr_1 = arr[indices]
print(sub_arr_1)

In [ ]:
sub_arr_boolean = arr[arr > 50]
print("Orignial Array:\n",arr)
# Boolean Indexing
print("After Boolean Condition:",arr[arr>50])

In [ ]:
idx_arr=np.array([[1,2],
[5,6]])
sub_arr_2=arr[idx_arr]
print(sub_arr_2)

In [ ]:
arr = np.arange(16).reshape(4, 4)
print("Mảng gốc ban đầu:\n arr = ", arr)
#Lấy các phần tử arr[3, 1], arr[3, 2] và arr[3, 3]
sub_arr = arr[3, [1, 2, 3]]
print("Mảng con: sub_arr = ", sub_arr)

Mảng gốc ban đầu:
 arr =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Mảng con: sub_arr =  [13 14 15]


In [ ]:
sub_arr = arr[1:, [1, 2, 3]]
print("Mảng con sub_arr:\n", sub_arr)

Mảng con sub_arr:
 [[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [ ]:
arr=np.array([[1,2,3],
[4,5,6],
[7,8,9]])
masks=arr[0,:]%2 == 0 
print("masks:",masks)
sub_arr=arr[:,masks] 
print("Mảng con mới: \n", sub_arr)

masks: [False  True False]
Mảng con mới: 
 [[2]
 [5]
 [8]]


In [ ]:
pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 577.4 kB/s eta 0:00:19
   - -------------------------------------- 0.5/11.0 MB 577.4 kB/s eta 0:00:19
   -- ------------------------------------- 0.8/11.0 MB 578.0 kB/s eta 0:00:18
   -- ------------------------------------- 0.8/11.0 MB 578.0 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/11.0 MB 578.3 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/11.0 MB 578.3 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/11.0 MB 578.3 kB/s eta 0:00:18
   ---- ----------------------------------- 1.3/11.0 MB 573.3 kB/s eta 0:00:17
   ----- ---------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import pandas as pd
pd.__version__

'2.3.3'